; ============================================================
; PPAS PHP-FPM Pool Ayarları
; 40 client (1 req/dk) + web UI için optimize edilmiş
;BU AYARLAR 40 CLİENT İÇİN OPTİMİZE EDİLMİŞTİR. DAHA FAZLA CLİENT İÇİN AYARLAR GÜNCELLENMELİDİR.(AHMET CAN YAMAÇ)

[www]
pm = dynamic
pm.max_children = 20
pm.start_servers = 8
pm.min_spare_servers = 4
pm.max_spare_servers = 12
pm.max_requests = 1000
pm.process_idle_timeout = 10s
