services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppas_php
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - ppas

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppas_worker
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=600
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - ppas

  nginx:
    image: nginx:stable
    container_name: ppas_nginx
    ports:
      - "127.0.0.1:9002:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped   
    networks:
      - ppas

  mysql:
    image: mysql:8
    container_name: ppas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Ppas_Secure_Root_2026_!#
      MYSQL_DATABASE: ppas_db
      MYSQL_USER: web_ppas
      MYSQL_PASSWORD: Ppas_App_Pass_2026_Security_#$
    ports:
      - "0.0.0.0:3307:3306"
    volumes:
      - /mnt/HC_Volume_104488791/mysql/ppas_mysql_data:/var/lib/mysql
    networks:
      - ppas

  redis:
    image: redis:7
    container_name: ppas_redis
    command: redis-server --save "" --appendonly no
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
    networks:
      - ppas

networks:
  ppas:

#volumes:
#  ppas_mysql_data:
